site_name: Capstone Group 2

pages:
  - Home: index.md
  - Vison Document: visionDoc.md
  - Supplementary Specification: suppSpec.md
  - Glossary : glossary.md
  - Use Case Model : use_case_model.md
theme: material